#!/usr/bin/env python3
"""
Generate sealed_envelope.json — known-answer vectors for the event-log sealed box
(libsodium crypto_box_seal, ADR-015 / CRYPTO.md §4 / PROTOCOL.md §6).

Reference implementation: PyNaCl (a thin wrapper over real libsodium). The vectors
this emits are the ground truth that the Kotlin SealedBox (ion-spin libsodium
bindings) must interoperate with byte-for-byte.

Two kinds of vector are produced:

  1. A DETERMINISTIC sealed box built from a FIXED ephemeral key, reconstructing
     crypto_box_seal by hand from libsodium primitives:
         eph_pk = scalarmult_base(eph_sk)
         nonce  = BLAKE2b-192(eph_pk || recipient_pk)        # unkeyed, 24-byte
         ct     = crypto_box(msg, nonce, recipient_pk, eph_sk)  # X25519 + XSalsa20-Poly1305
         sealed = eph_pk || ct
     Because the ephemeral key is fixed, the sealed bytes are stable and can be
     pinned. We then assert PyNaCl's HIGH-LEVEL SealedBox.decrypt() (real libsodium
     crypto_box_seal_open) recovers the plaintext — proving the hand-built box is a
     genuine, libsodium-openable sealed box, not a look-alike.

  2. The recipient + a DIFFERENT "child" keypair, so the Kotlin test can assert the
     child (which holds neither the recipient priv nor any decryption-capable secret)
     CANNOT open the box — the load-bearing "child cannot read own log" property.

Run:  python gen_sealed_envelope.py   (requires `pip install pynacl`)
Determinism: all keys + the ephemeral are fixed seeds below, so re-running yields
byte-identical output. Do not change the seeds without regenerating + re-pinning.
"""
import json
import nacl.bindings as b
from nacl.public import PrivateKey, PublicKey, SealedBox
from nacl.hash import blake2b
from nacl.encoding import RawEncoder

# ---- fixed seeds (32 bytes each) — recognizable, NOT secret, vectors only ----
RECIPIENT_SK = bytes.fromhex("01" * 32)   # parent X25519 private (the audience)
CHILD_SK     = bytes.fromhex("02" * 32)   # an unrelated child X25519 key (must NOT decrypt)
EPHEMERAL_SK = bytes.fromhex("03" * 32)   # fixed sender ephemeral -> deterministic sealed bytes

# Canonical (RFC 8785 JCS: sorted keys) event plaintext, §6.1 schema.
PLAINTEXT = b'{"at_ms":1734307200000,"data":{"pkg":"com.example.game"},"kind":"APP_LAUNCH"}'


def hx(x: bytes) -> str:
    return x.hex()


def crypto_box_seal_deterministic(msg: bytes, recipient_pk: bytes, eph_sk: bytes) -> bytes:
    """Reconstruct libsodium crypto_box_seal with a caller-fixed ephemeral key."""
    eph_pk = b.crypto_scalarmult_base(eph_sk)
    nonce = blake2b(eph_pk + recipient_pk, digest_size=24, encoder=RawEncoder)  # libsodium sealed-box nonce
    ct = b.crypto_box(msg, nonce, recipient_pk, eph_sk)  # XSalsa20-Poly1305 over X25519 shared secret
    return eph_pk + ct


def main() -> None:
    recipient = PrivateKey(RECIPIENT_SK)
    recipient_pk = bytes(recipient.public_key)
    child = PrivateKey(CHILD_SK)

    # (1) deterministic, byte-pinnable sealed box
    sealed = crypto_box_seal_deterministic(PLAINTEXT, recipient_pk, EPHEMERAL_SK)

    # self-check A: real libsodium crypto_box_seal_open recovers the plaintext
    opened = SealedBox(recipient).decrypt(sealed)
    assert opened == PLAINTEXT, "PyNaCl SealedBox failed to open the hand-built box"

    # self-check B: the child key cannot open it
    try:
        SealedBox(child).decrypt(sealed)
        raise SystemExit("FATAL: child key opened the box — vector is broken")
    except Exception:
        pass  # expected: CryptoError

    # SEAL_OVERHEAD = 32 (ephemeral pub) + 16 (Poly1305 tag)
    assert len(sealed) == len(PLAINTEXT) + 48, "unexpected sealed length"

    vector = {
        "_comment": "Known-answer vectors for event-log crypto_box_seal (ADR-015, CRYPTO.md §4). "
                    "Generated by gen_sealed_envelope.py over PyNaCl/libsodium. The Kotlin "
                    "SealedBox (ion-spin libsodium) MUST open `sealed_hex` to `plaintext_utf8` "
                    "under the recipient keypair, and the child keypair MUST fail.",
        "nonce_hash": "BLAKE2b-192(ephemeral_pub || recipient_pub), libsodium crypto_box_seal — NOT BLAKE3",
        "recipient_x25519_priv_hex": hx(RECIPIENT_SK),
        "recipient_x25519_pub_hex": hx(recipient_pk),
        "child_x25519_priv_hex": hx(CHILD_SK),
        "child_x25519_pub_hex": hx(bytes(child.public_key)),
        "ephemeral_x25519_priv_hex": hx(EPHEMERAL_SK),
        "plaintext_utf8": PLAINTEXT.decode(),
        "plaintext_hex": hx(PLAINTEXT),
        "sealed_hex": hx(sealed),
        "sealed_len": len(sealed),
        "seal_overhead_bytes": 48,
        "open_recovers": True,
        "child_open_fails": True,
    }
    with open("sealed_envelope.json", "w", encoding="utf-8") as f:
        json.dump(vector, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print("recipient_pub:", hx(recipient_pk))
    print("sealed_len:   ", len(sealed))
    print("sealed_hex:   ", hx(sealed))
    print("wrote sealed_envelope.json — self-checks passed")


if __name__ == "__main__":
    main()
